<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>feather</string>
		</array>
		<key>firstLineMatch</key>
		<string></string>
		<key>name</key>
		<string>Feather</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>match</key>
				<string>(?i)(?!\w+\:)\b(Undefined|String|Real|Bool|(Array(\&lt;.+\&gt;)?)|(Enum\.\w+)|Pointer|(Struct(\.\w*)?)|(Id(\.\w*)?)(\&lt;.+\&gt;)?|(Asset(\.\w*)?)|(Constant(\.\w*)?)|ArgumentIdentity|Any(\*)?|Unset)</string>
				<key>name</key>
				<string>keyword.control.feather</string>
			</dict>

			<!-- Minimal GML Support -->
			<dict>
				<key>begin</key>
				<string>\b(Enum)\s+(\{)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.control.gml</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.block.begin.gml</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\}</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.block.end.gml</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b([a-zA-Z_][a-zA-Z0-9_]*)\,?\b</string>
						<key>name</key>
						<string>variable.other.enummember.gml</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>match</key>
				<string>\b([Ff]unction)(\s*([a-zA-Z_][a-zA-Z0-9_]*))?\b</string>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.control.gml</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.name.function.gml</string>
					</dict>
				</dict>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(undefined|true|false|global|self|other)\b</string>
				<key>name</key>
				<string>support.constant.gml</string>
			</dict>
			<dict>
				<!-- NOTE Not the full list of built-in variables, but these might be considered "native" by
						  most users and thus expect immediate tokenization rather than waiting for the server -->
				<key>match</key>
				<string>\b(alarm|async_load|argument\d*)\b</string>
				<key>name</key>
				<string>support.variable.gml</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(var|globalvar|constructor)\b</string>
				<key>name</key>
				<string>keyword.control.gml</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(\.\.\.|[a-zA-Z_][a-zA-Z0-9_]*)(?=\:)</string>
				<key>name</key>
				<string>variable.other.local.gml</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\{</string>
				<key>name</key>
				<string>punctuation.section.block.begin.gml</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\}</string>
				<key>name</key>
				<string>punctuation.section.block.end.gml</string>
			</dict>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>/\*</string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.comment.begin.gml</string>
							</dict>
						</dict>
						<key>end</key>
						<string>\*/</string>
						<key>endCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.comment.end.gml</string>
							</dict>
						</dict>
						<key>name</key>
						<string>comment.block.gml</string>
					</dict>
					<dict>
						<key>begin</key>
						<string>//</string>
						<key>end</key>
						<string>\n</string>
						<key>name</key>
						<string>comment.line.double-slash.gml</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>match</key>
				<string>%</string>
				<key>name</key>
				<string>meta.underline-flag.gml</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
		</dict>
		<key>scopeName</key>
		<string>source.feather</string>
		<key>uuid</key>
		<string>a101fe7b-98a6-4db0-8ea9-532172e20768</string>
	</dict>
</plist>