<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>vsh</string>
			<string>fsh</string>
		</array>
		<key>firstLineMatch</key>
		<string></string>
		<key>name</key>
		<string>GLSL</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>name</key>
				<string>keyword.control.glsl</string>
				<key>match</key>
				<string>\b(if|else|switch|case|default|for|while|do|break|continue|return|discard|struct|defined)\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>storage.type.glsl</string>
				<key>match</key>
				<string>\b(void|bool|int|uint|float|double|bvec[2|3|4]|ivec[2|3|4]|uvec[2|3|4]|vec[2|3|4]|dvec[2|3|4]|mat[2|3|4]|mat2x2|mat2x3|mat2x4|mat3x2|mat3x3|mat3x4|mat4x2|mat4x3|mat4x4|dmat[2|3|4]|dmat2x2|dmat2x3|dmat2x4|dmat3x2|dmat3x3|dmat3x4|dmat4x2|dmat4x3|dmat4x4|sampler[1|2|3]D|[i|u]sampler[1|2|3]D|samplerCube|[i|u]samplerCube|sampler2DRect|[i|u]sampler2DRect|sampler[1|2]DArray|[i|u]sampler[1|2]DArray|samplerCubeArray|[i|u]samplerCubeArray|samplerBuffer|[i|u]samplerBuffer|sampler2DMS|[i|u]sampler2DMS|sampler2DMSArray|[i|u]sampler2DMSArray|sampler[1|2]DShadow|samplerCubeShadow|sampler2DRectShadow|sampler[1|2]DArrayShadow|samplerCubeArrayShadow|image[1|2|3]D|[i|u]image[1|2|3]D|imageCube|[i|u]imageCube|image2DRect|[i|u]image2DRect|image[1|2]DArray|[i|u]image[1|2]DArray|imageCubeArray|[i|u]imageCubeArray|imageBuffer|[i|u]imageBuffer|image2DMS|[i|u]image2DMS|image2DMSArray|[i|u]image2DMSArray|atomic_uint)\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>keyword.control.glsl</string> <!-- Technically a storage.modifier.glsl, but it must be paired with a keyword.* -->
				<key>match</key>
				<string>\b(const|in|out|inout|attribute|uniform|varying|buffer|shared|centroid|sample|patch|layout|smooth|flat|noperspective|highp|mediump|lowp|invariant|precise|precision|coherent|volatile|restrict|readonly|writeonly)\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>support.constant.glsl</string>
				<key>match</key>
				<string>\b(true|false|pi)\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>meta.preprocessor.glsl</string>
				<key>begin</key>
				<string>\#</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.directive.begin.glsl</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\n</string>
			</dict>
			<dict>
				<key>name</key>
				<string>constant.language.boolean.glsl</string>
				<key>match</key>
				<string>\b(true|false)\b</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?x)
					(  (?i:
					\$ ([0-9A-Fa-f]+)?        # Hexadecimal
					|  \b 0x ([0-9A-Fa-f]+)?  # Hexadecimal
					|  \b    ([0-9]+[0-9]*)   # Decimal
					|      (\#(([A-Fa-f0-9]{2}){1,3})\b)
					)
					|  \b([0-9]+[0-9]*)?(\.\B|\.([0-9]+)\b)
					)</string>
				<key>name</key>
				<string>constant.numeric.glsl</string>
			</dict>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>/\*</string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.comment.begin.glsl</string>
							</dict>
						</dict>
						<key>end</key>
						<string>\*/</string>
						<key>endCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.comment.end.glsl</string>
							</dict>
						</dict>
						<key>name</key>
						<string>comment.block.glsl</string>
					</dict>
					<dict>
						<key>begin</key>
						<string>//</string>
						<key>end</key>
						<string>\n</string>
						<key>name</key>
						<string>comment.line.double-slash.glsl</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>include</key>
				<string>#block</string>
			</dict>
			<dict>
				<key>name</key>
				<string>support.variable</string>
				<key>match</key>
				<string>\b(gm_BaseTexture|gm_Matrices|gm_LightingEnabled|gm_VS_FogEnabled|gm_FogStart|gm_RcpFogRange|gm_PS_FogEnabled|gm_FogColour|gm_AlphaTestEnabled|gm_AlphaRefValue)\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>support.constant</string>
				<key>match</key>
				<string>\b(x|y|z|w|r|g|b|a|s|t|q|p|xyzw|xyz|xy|rgba|rgb|bgr|gbra|grba|bgra|brga|rbga|s[0-7]|c([01]?[0-9][0-9]?|2[0-4][0-9]|250)|MAX_VS_LIGHTS|MATRIX_VIEW|MATRIX_PROJECTION|MATRIX_WORLD|MATRIX_WORLD_VIEW|MATRIX_WORLD_VIEW_PROJECTION|MATRIX_MAX|__LINE__|__FILE__|__VERSION__|GL_ES)\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>support.function</string>
				<key>match</key>
				<string>\b(abs|acos|all|any|asin|atan|atan2|ceil|clamp|clip|cos|cosh|cross|D3DCOLORtoUBYTE4|ddx9xddy|degrees|determinant|distance|dot|exp|exp2|faceforward|floor|fmod|frac|frexp|fwidth|isfinite|isinf|isnan|ldexp|len|length|lerp|lit|log|log10|log2|max|min|modf|mul|noise|normalize|pow|radians|reflect|refract|round|rsqrt|saturate|sign|sin|sincos|sinh|smoothstep|sqrt|step|tan|tanh|tex1D|tex1Dbias|tex1Dgrad|tex1Dlod|tex1Dproj|tex2D|tex2Dbias|tex2Dgrad|tex2Dlod|tex2Dproj|tex3D|tex3Dbias|tex3Dgrad|tex3Dlod|tex3Dproj|texCUBE|texCUBE|texCUBEbias|texCUBEgrad|texCUBElod|texCUBEproj|transpose|trunc)\b</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>block</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>\{</string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.section.block.begin.glsl</string>
							</dict>
						</dict>
						<key>end</key>
						<string>\}</string>
						<key>endCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.section.block.end.glsl</string>
							</dict>
						</dict>
						<key>name</key>
						<string>meta.block.glsl</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#block_contents</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>block_contents</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#block</string>
					</dict>
					<dict>
						<key>include</key>
						<string>$base</string>
					</dict>
				</array>
			</dict>
			<key>parens</key>
			<dict>
				<key>begin</key>
				<string>\(</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.parens.begin.glsl</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\)</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.parens.end.glsl</string>
					</dict>
				</dict>
				<key>name</key>
				<string>meta.parens.glsl</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>$base</string>
					</dict>
				</array>
			</dict>
		</dict>
		<key>scopeName</key>
		<string>source.glsl</string>
		<key>uuid</key>
		<string>c358e901-bcdc-486b-9822-76a237f1d518</string>
	</dict>
</plist>
